DROP TABLE MAGNESIUM_FINAL;
DROP TABLE POTASSIUM_FINAL;
DROP TABLE COMPLETE_DRUG_TABLE_FINAL;
DROP TABLE NURSE_NOTE_FINAL;
DROP TABLE HEART_RATE_FINAL;


-- CREATE TABLE MAGNESIUM_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE, 
-- "VALUENUM" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0)
-- );

-- CREATE TABLE POTASSIUM_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE, 
-- "VALUENUM" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0)
-- );

-- CREATE TABLE COMPLETE_DRUG_TABLE_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE,
-- "VALUENUM" NUMERIC (7,0)
-- );

-- CREATE TABLE NURSE_NOTE_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE,
-- "NOTE" TEXT
-- );

-- CREATE TABLE HEART_RATE_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE,
-- "VALUENUM" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0)
-- );

CREATE TABLE FILTER AS 
(
SELECT 
	ICUSTAY_ID
FROM
	mimiciii.icustay_detail
WHERE
	AGE > 18.0 AND 
	FIRST_ICU_STAY = 'Y'
ORDER BY 
	ICUSTAY_ID
);


CREATE TABLE MAGNESIUM_FINAL AS
(
SELECT DISTINCT 
	chartevents.ICUSTAY_ID,
	chartevents.ITEMID, 
	chartevents.CHARTTIME,
	chartevents.VALUENUM
FROM
	mimiciii.chartevents
INNER JOIN FILTER 
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
);


CREATE TABLE POTASSIUM_FINAL AS 
(
SELECT DISTINCT 
	chartevents.ICUSTAY_ID,
	chartevents.ITEMID,
	chartevents.CHARTTIME,
	chartevents.VALUENUM
FROM
	mimiciii.chartevents
INNER JOIN FILTER
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
);

CREATE TABLE FILTER_NURSE_NOTE AS
(
SELECT 
	HADM_ID,
	ICUSTAY_ID
FROM
	mimiciii.icustay_detail
WHERE
	AGE > 18.0 AND 
	FIRST_ICU_STAY = 'Y'
ORDER BY 
	HADM_ID
);


CREATE TABLE NURSE_NOTE_FINAL AS
(
SELECT DISTINCT
	noteevents.HADM_ID, 
	noteevents.CHARTTIME, 
	noteevents.TEXT AS NOTE

FROM mimiciii.noteevents 

INNER JOIN FILTER_NURSE_NOTE
ON FILTER_NURSE_NOTE.HADM_ID = noteevents.HADM_ID
WHERE CATEGORY LIKE '%nursing%'
);


CREATE TABLE HEART_RATE_FINAL AS
(
SELECT DISTINCT
	chartevents.ICUSTAY_ID, 
	chartevents.CHARTTIME, 
	chartevents.VALUENUM, 
	chartevents.ITEMID
FROM 
	mimiciii.chartevents 
INNER JOIN FILTER 
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
WHERE ITEMID in ('211', '220045')
);


CREATE TABLE COMPLETE_DRUG_TABLE_FINAL AS
(
SELECT DISTINCT
	chartevents.ICUSTAY_ID,
	chartevents.ITEMID,
	chartevents.CHARTTIME,
	chartevents.VALUENUM
FROM 
	mimiciii.chartevents
INNER JOIN FILTER
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
WHERE ITEMID IN ('1035', '1686', '2244', '2526', '4789', '5416', '12979', '15471', '221429', '2953', '30117', '30052', '45853', '222151', '30115', '221468', '2478', '7158', '30112', '42342', '221347', '228339', '30048', '225945', '4649', '221282', '225974', '221429', '2953', '30117', '30052', '45853', '222151', '30115', '221468', '2478', '7158', '30112', '42342', '221347', '228339', '30048', '225945', '4649', '221282', '225974')
);



