DROP TABLE MAGNESIUM_FINAL;
DROP TABLE POTASSIUM_FINAL;
DROP TABLE COMPLETE_DRUG_TABLE_FINAL;
DROP TABLE NURSE_NOTE_FINAL;
DROP TABLE HEART_RATE_FINAL;


-- CREATE TABLE MAGNESIUM_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE, 
-- "VALUENUM" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0)
-- );

-- CREATE TABLE POTASSIUM_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE, 
-- "VALUENUM" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0)
-- );

-- CREATE TABLE COMPLETE_DRUG_TABLE_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE,
-- "VALUENUM" NUMERIC (7,0)
-- );

-- CREATE TABLE NURSE_NOTE_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE,
-- "NOTE" TEXT
-- );

-- CREATE TABLE HEART_RATE_FINAL
-- (
-- "ICUSTAY_ID" NUMERIC (7,0),
-- "CHARTTIME" TIMESTAMP (9) WITH TIME ZONE,
-- "VALUENUM" NUMERIC (7,0),
-- "ITEMID" NUMERIC (7,0)
-- );

CREATE TABLE FILTER AS 
(
SELECT 
	ICUSTAY_ID
FROM
	mimiciii.icustay_detail
WHERE
	AGE > 18.0 AND 
	FIRST_ICU_STAY = 'Y'
ORDER BY 
	ICUSTAY_ID
);


CREATE TABLE MAGNESIUM_FINAL AS
(
SELECT DISTINCT 
	chartevents.ICUSTAY_ID,
	chartevents.ITEMID, 
	chartevents.CHARTTIME,
	chartevents.VALUENUM
FROM
	mimiciii.chartevents
INNER JOIN FILTER 
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
);


CREATE TABLE POTASSIUM_FINAL AS 
(
SELECT DISTINCT 
	chartevents.ICUSTAY_ID,
	chartevents.ITEMID,
	chartevents.CHARTTIME,
	chartevents.VALUENUM
FROM
	mimiciii.chartevents
INNER JOIN FILTER
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
);


CREATE TABLE NURSE_NOTE_FINAL AS
(
SELECT DISTINCT
	notevents.ICUSTAY_ID, 
	notevents.CHARTTIME, 
	noteevents.TEXT AS NOTE
FROM NOTEVENTS
WHERE CATEGORY LIKE '%nursing%'
INNER JOIN FILTER 
ON FILTER.ICUSTAY_ID = notevents.ICUSTAY_ID
);


CREATE TABLE HEART_RATE_FINAL AS
(
SELECT DISTINCT
	chartevents.ICUSTAY_ID, 
	chartevents.CHARTTIME, 
	chartevents.VALUENUM, 
	chartevents.ITEMID
FROM mimiciii.chartevents 
WHERE ITEMID in ('211, 220045')
INNER JOIN FILTER 
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
);


CREATE TABLE COMPLETE_DRUG_TABLE AS
(
SELECT DISTINCT
	chartevents.ICUSTAY_ID,
	chartevents.ITEMID,
	chartevents.CHARTTIME,
	chartevents.VALUENUM
FROM 
	mimiciii.chartevents
WHERE ITEMID IN ('1035', '1686', '2244', '2526', '4789', '5416', '12979', '15471', '221429', '2953', '30117', '30052', '45853', '222151', '30115', '221468', '2478', '7158', '30112', '42342', '221347', '228339', '30048', '225945', '4649', '221282', '225974', '221429', '2953', '30117', '30052', '45853', '222151', '30115', '221468', '2478', '7158', '30112', '42342', '221347', '228339', '30048', '225945', '4649', '221282', '225974')
INNER JOIN FILTER
ON FILTER.ICUSTAY_ID = chartevents.ICUSTAY_ID
);


-- INSERT INTO MAGNESIUM_FINAL ("ICUSTAY_ID", "CHARTTIME", "VALUENUM", "ITEMID")
-- SELECT ICUSTAY_ID, CHARTTIME, VALUENUM, ITEMID FROM MAGNESIUM;

-- INSERT INTO POTASSIUM_FINAL ("ICUSTAY_ID", "CHARTTIME", "VALUENUM", "ITEMID")
-- SELECT ICUSTAY_ID, CHARTTIME, VALUENUM, ITEMID FROM POTASSIUM;

-- INSERT INTO COMPLETE_DRUG_TABLE_FINAL ("ICUSTAY_ID", "ITEMID", "CHARTTIME", "VALUENUM")
-- SELECT ICUSTAY_ID, ITEMID, CHARTTIME, VALUENUM FROM COMPLETE_DRUG_TABLE;

-- INSERT INTO NURSE_NOTE_FINAL ("ICUSTAY_ID", "CHARTTIME", "NOTE")
-- SELECT ICUSTAY_ID, CHARTTIME, NOTE FROM NURSE_NOTE;

-- INSERT INTO HEART_RATE_FINAL ("ICUSTAY_ID", "CHARTTIME", "VALUENUM", "ITEMID")
-- SELECT ICUSTAY_ID, CHARTTIME, VALUENUM, ITEMID FROM HEART_RATE;



